import { DatabaseSync } from 'node:sqlite';
import { randomUUID, createHash } from 'node:crypto';

export const roles=['resident','guard','manager','accountant'];
export function createCore(path=':memory:'){
 const db=new DatabaseSync(path);db.exec('PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL;');
 db.exec(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,name_fa TEXT,name_en TEXT,role TEXT NOT NULL,unit_id TEXT);
 CREATE TABLE IF NOT EXISTS units(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,code TEXT UNIQUE NOT NULL,balance INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS guests(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,unit_id TEXT NOT NULL,guest_name TEXT NOT NULL,type TEXT NOT NULL,status TEXT NOT NULL,valid_until TEXT,version INTEGER NOT NULL DEFAULT 1,created_by TEXT,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS tickets(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,unit_id TEXT,category TEXT NOT NULL,title TEXT NOT NULL,priority TEXT NOT NULL,status TEXT NOT NULL,assignee TEXT,version INTEGER NOT NULL DEFAULT 1,created_by TEXT,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS bookings(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,unit_id TEXT NOT NULL,amenity TEXT NOT NULL,start_at TEXT NOT NULL,end_at TEXT NOT NULL,status TEXT NOT NULL,created_by TEXT,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS receipts(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,unit_id TEXT NOT NULL,amount INTEGER NOT NULL,status TEXT NOT NULL,fingerprint TEXT UNIQUE,created_by TEXT,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS audit(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,actor_id TEXT NOT NULL,action TEXT NOT NULL,resource TEXT NOT NULL,resource_id TEXT,request_id TEXT NOT NULL,created_at TEXT NOT NULL);`);
 const now=()=>new Date().toISOString(); const id=()=>randomUUID();
 const audit=(ctx,action,resource,resourceId)=>db.prepare('INSERT INTO audit VALUES(?,?,?,?,?,?,?,?)').run(id(),ctx.tenantId,ctx.user.id,action,resource,resourceId||null,ctx.requestId||id(),now());
 const requireRole=(ctx,...allowed)=>{if(!ctx?.user||ctx.user.tenant_id!==ctx.tenantId)throw err(401,'UNAUTHENTICATED');if(!allowed.includes(ctx.user.role))throw err(403,'FORBIDDEN')};
 const ownUnit=(ctx,unitId)=>ctx.user.role==='resident'&&ctx.user.unit_id!==unitId?(()=>{throw err(403,'FORBIDDEN')})():true;
 const list=(sql,...args)=>db.prepare(sql).all(...args);
 return {db,seed(){const tenant='lavizan-demo';const units=[['u-a704','A7-04',25000000],['u-b302','B3-02',0],['u-c108','C1-08',8000000]];for(const [uid,code,b] of units)db.prepare('INSERT OR IGNORE INTO units VALUES(?,?,?,?)').run(uid,tenant,code,b);const users=[['resident-1','امیر رضایی','Amir Rezaei','resident','u-a704'],['guard-1','رضا نگهبان','Reza Guard','guard',null],['manager-1','مریم مدیر','Maryam Manager','manager',null],['accountant-1','سارا حسابدار','Sara Accountant','accountant',null]];for(const u of users)db.prepare('INSERT OR IGNORE INTO users VALUES(?,?,?,?,?,?)').run(u[0],tenant,u[1],u[2],u[3],u[4]);if(!db.prepare('SELECT 1 FROM guests LIMIT 1').get())db.prepare('INSERT INTO guests VALUES(?,?,?,?,?,?,?,?,?,?)').run('g-1',tenant,'u-a704','حسین احمدی','personal','waiting',new Date(Date.now()+3600000).toISOString(),1,'resident-1',now());if(!db.prepare('SELECT 1 FROM tickets LIMIT 1').get())db.prepare('INSERT INTO tickets VALUES(?,?,?,?,?,?,?,?,?,?,?)').run('t-1',tenant,'u-a704','technical','نشتی پارکینگ B','critical','submitted',null,1,'resident-1',now());},context(userId,requestId=id()){const user=db.prepare('SELECT * FROM users WHERE id=?').get(userId);if(!user)throw err(401,'UNAUTHENTICATED');return {user,tenantId:user.tenant_id,requestId}},
 hub(ctx){requireRole(ctx,...roles);const common={role:ctx.user.role,user:{id:ctx.user.id,name_fa:ctx.user.name_fa,name_en:ctx.user.name_en,unit_id:ctx.user.unit_id}};if(ctx.user.role==='resident')return {...common,unit:db.prepare('SELECT * FROM units WHERE id=?').get(ctx.user.unit_id),guests:list('SELECT * FROM guests WHERE tenant_id=? AND unit_id=? ORDER BY created_at DESC',ctx.tenantId,ctx.user.unit_id),tickets:list('SELECT * FROM tickets WHERE tenant_id=? AND unit_id=? ORDER BY created_at DESC',ctx.tenantId,ctx.user.unit_id),bookings:list('SELECT * FROM bookings WHERE tenant_id=? AND unit_id=?',ctx.tenantId,ctx.user.unit_id)};if(ctx.user.role==='guard')return {...common,guests:list("SELECT * FROM guests WHERE tenant_id=? AND status IN ('waiting','approved','entered')",ctx.tenantId)};if(ctx.user.role==='manager')return {...common,tickets:list("SELECT * FROM tickets WHERE tenant_id=? AND status NOT IN ('closed') ORDER BY CASE priority WHEN 'critical' THEN 1 WHEN 'urgent' THEN 2 ELSE 3 END",ctx.tenantId)};return {...common,receipts:list("SELECT r.*,u.code unit_code FROM receipts r JOIN units u ON u.id=r.unit_id WHERE r.tenant_id=? AND r.status='submitted'",ctx.tenantId)}},
 createGuest(ctx,input){requireRole(ctx,'resident');const gid=id();db.prepare('INSERT INTO guests VALUES(?,?,?,?,?,?,?,?,?,?)').run(gid,ctx.tenantId,ctx.user.unit_id,input.name,input.type||'personal','approved',input.valid_until||new Date(Date.now()+7200000).toISOString(),1,ctx.user.id,now());audit(ctx,'guest.create','guest',gid);return db.prepare('SELECT * FROM guests WHERE id=?').get(gid)},
 transitionGuest(ctx,gid,status,expectedVersion){requireRole(ctx,'resident','guard','manager');const g=db.prepare('SELECT * FROM guests WHERE id=? AND tenant_id=?').get(gid,ctx.tenantId);if(!g)throw err(404,'NOT_FOUND');if(ctx.user.role==='resident')ownUnit(ctx,g.unit_id);const allowed={waiting:['approved','rejected'],approved:['entered','rejected'],entered:['exited']}[g.status]||[];if(!allowed.includes(status))throw err(409,'INVALID_TRANSITION');if(g.version!==expectedVersion)throw err(409,'CONFLICT');db.prepare('UPDATE guests SET status=?,version=version+1 WHERE id=?').run(status,gid);audit(ctx,`guest.${status}`,'guest',gid);return db.prepare('SELECT * FROM guests WHERE id=?').get(gid)},
 createTicket(ctx,input){requireRole(ctx,'resident');const tid=id();db.prepare('INSERT INTO tickets VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(tid,ctx.tenantId,ctx.user.unit_id,input.category,input.title,input.priority||'normal','submitted',null,1,ctx.user.id,now());audit(ctx,'ticket.create','ticket',tid);return db.prepare('SELECT * FROM tickets WHERE id=?').get(tid)},
 transitionTicket(ctx,tid,input){requireRole(ctx,'manager');const t=db.prepare('SELECT * FROM tickets WHERE id=? AND tenant_id=?').get(tid,ctx.tenantId);if(!t)throw err(404,'NOT_FOUND');if(t.version!==input.expected_version)throw err(409,'CONFLICT');db.prepare('UPDATE tickets SET status=?,assignee=?,version=version+1 WHERE id=?').run(input.status,input.assignee||t.assignee,tid);audit(ctx,`ticket.${input.status}`,'ticket',tid);return db.prepare('SELECT * FROM tickets WHERE id=?').get(tid)},
 createBooking(ctx,input){requireRole(ctx,'resident');const clash=db.prepare("SELECT 1 FROM bookings WHERE tenant_id=? AND amenity=? AND status='confirmed' AND start_at < ? AND end_at > ?").get(ctx.tenantId,input.amenity,input.end_at,input.start_at);if(clash)throw err(409,'BOOKING_CONFLICT');const bid=id();db.prepare('INSERT INTO bookings VALUES(?,?,?,?,?,?,?,?,?)').run(bid,ctx.tenantId,ctx.user.unit_id,input.amenity,input.start_at,input.end_at,'confirmed',ctx.user.id,now());audit(ctx,'booking.confirm','booking',bid);return db.prepare('SELECT * FROM bookings WHERE id=?').get(bid)},
 submitReceipt(ctx,input){requireRole(ctx,'resident');const fp=createHash('sha256').update(`${ctx.user.unit_id}|${input.amount}|${input.paid_at}`).digest('hex');const rid=id();try{db.prepare('INSERT INTO receipts VALUES(?,?,?,?,?,?,?,?)').run(rid,ctx.tenantId,ctx.user.unit_id,input.amount,'submitted',fp,ctx.user.id,now())}catch{throw err(409,'DUPLICATE_RECEIPT')}audit(ctx,'receipt.submit','receipt',rid);return db.prepare('SELECT * FROM receipts WHERE id=?').get(rid)},
 reviewReceipt(ctx,rid,status){requireRole(ctx,'accountant');if(!['approved','rejected'].includes(status))throw err(422,'VALIDATION_FAILED');const r=db.prepare('SELECT * FROM receipts WHERE id=? AND tenant_id=?').get(rid,ctx.tenantId);if(!r)throw err(404,'NOT_FOUND');db.prepare('UPDATE receipts SET status=? WHERE id=?').run(status,rid);audit(ctx,`receipt.${status}`,'receipt',rid);return db.prepare('SELECT * FROM receipts WHERE id=?').get(rid)},
 auditLog(ctx){requireRole(ctx,'manager','accountant');return list('SELECT * FROM audit WHERE tenant_id=? ORDER BY created_at DESC',ctx.tenantId)}}}
export function err(status,code,message=code){return Object.assign(new Error(message),{status,code})}
