import { DatabaseSync } from 'node:sqlite';
import { randomUUID, createHash } from 'node:crypto';

export const roles=['resident','guard','manager','accountant'];
export function createCore(path=':memory:'){
 const db=new DatabaseSync(path);db.exec('PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL;');
 db.exec(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,name_fa TEXT,name_en TEXT,role TEXT NOT NULL,unit_id TEXT);
 CREATE TABLE IF NOT EXISTS units(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,code TEXT UNIQUE NOT NULL,balance INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS guests(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,unit_id TEXT NOT NULL,guest_name TEXT NOT NULL,type TEXT NOT NULL,status TEXT NOT NULL,valid_until TEXT,version INTEGER NOT NULL DEFAULT 1,created_by TEXT,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS tickets(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,unit_id TEXT,category TEXT NOT NULL,title TEXT NOT NULL,priority TEXT NOT NULL,status TEXT NOT NULL,assignee TEXT,version INTEGER NOT NULL DEFAULT 1,created_by TEXT,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS bookings(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,unit_id TEXT NOT NULL,amenity TEXT NOT NULL,start_at TEXT NOT NULL,end_at TEXT NOT NULL,status TEXT NOT NULL,created_by TEXT,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS receipts(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,unit_id TEXT NOT NULL,amount INTEGER NOT NULL,status TEXT NOT NULL,fingerprint TEXT UNIQUE,created_by TEXT,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS packages(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,unit_id TEXT NOT NULL,carrier TEXT,reference TEXT,status TEXT NOT NULL,received_by TEXT,collected_by TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS notices(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,title_fa TEXT NOT NULL,title_en TEXT,body_fa TEXT NOT NULL,body_en TEXT,audience TEXT NOT NULL,status TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,created_by TEXT,created_at TEXT NOT NULL,published_at TEXT);
 CREATE TABLE IF NOT EXISTS notification_intents(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,recipient_id TEXT,unit_id TEXT,kind TEXT NOT NULL,resource_id TEXT,payload TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS audit(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,actor_id TEXT NOT NULL,action TEXT NOT NULL,resource TEXT NOT NULL,resource_id TEXT,request_id TEXT NOT NULL,created_at TEXT NOT NULL);`);
 const now=()=>new Date().toISOString(); const id=()=>randomUUID();
 const audit=(ctx,action,resource,resourceId)=>db.prepare('INSERT INTO audit VALUES(?,?,?,?,?,?,?,?)').run(id(),ctx.tenantId,ctx.user.id,action,resource,resourceId||null,ctx.requestId||id(),now());
 const requireRole=(ctx,...allowed)=>{if(!ctx?.user||ctx.user.tenant_id!==ctx.tenantId)throw err(401,'UNAUTHENTICATED');if(!allowed.includes(ctx.user.role))throw err(403,'FORBIDDEN')};
 const ownUnit=(ctx,unitId)=>ctx.user.role==='resident'&&ctx.user.unit_id!==unitId?(()=>{throw err(403,'FORBIDDEN')})():true;
 const list=(sql,...args)=>db.prepare(sql).all(...args);
 return {db,seed(){const tenant='lavizan-demo';const units=[['u-a704','A7-04',25000000],['u-b302','B3-02',0],['u-c108','C1-08',8000000]];for(const [uid,code,b] of units)db.prepare('INSERT OR IGNORE INTO units VALUES(?,?,?,?)').run(uid,tenant,code,b);const users=[['resident-1','امیر رضایی','Amir Rezaei','resident','u-a704'],['guard-1','رضا نگهبان','Reza Guard','guard',null],['manager-1','مریم مدیر','Maryam Manager','manager',null],['accountant-1','سارا حسابدار','Sara Accountant','accountant',null]];for(const u of users)db.prepare('INSERT OR IGNORE INTO users VALUES(?,?,?,?,?,?)').run(u[0],tenant,u[1],u[2],u[3],u[4]);if(!db.prepare('SELECT 1 FROM guests LIMIT 1').get())db.prepare('INSERT INTO guests VALUES(?,?,?,?,?,?,?,?,?,?)').run('g-1',tenant,'u-a704','حسین احمدی','personal','waiting',new Date(Date.now()+3600000).toISOString(),1,'resident-1',now());if(!db.prepare('SELECT 1 FROM tickets LIMIT 1').get())db.prepare('INSERT INTO tickets VALUES(?,?,?,?,?,?,?,?,?,?,?)').run('t-1',tenant,'u-a704','technical','نشتی پارکینگ B','critical','submitted',null,1,'resident-1',now());if(!db.prepare('SELECT 1 FROM packages LIMIT 1').get())db.prepare('INSERT INTO packages VALUES(?,?,?,?,?,?,?,?,?,?)').run('p-1',tenant,'u-a704','پست','PKG-DEMO-1','received','guard-1',null,now(),now());if(!db.prepare('SELECT 1 FROM notices LIMIT 1').get())db.prepare('INSERT INTO notices VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run('n-1',tenant,'سرویس دوره‌ای آسانسور','Scheduled lift service','روز شنبه آسانسور بلوک B سرویس می‌شود.','Block B lift will be serviced on Saturday.','all','published',1,'manager-1',now(),now());},context(userId,requestId=id()){const user=db.prepare('SELECT * FROM users WHERE id=?').get(userId);if(!user)throw err(401,'UNAUTHENTICATED');return {user,tenantId:user.tenant_id,requestId}},
 hub(ctx){requireRole(ctx,...roles);const notices=list("SELECT * FROM notices WHERE tenant_id=? AND status='published' ORDER BY published_at DESC",ctx.tenantId);const common={role:ctx.user.role,user:{id:ctx.user.id,name_fa:ctx.user.name_fa,name_en:ctx.user.name_en,unit_id:ctx.user.unit_id},notices};if(ctx.user.role==='resident')return {...common,unit:db.prepare('SELECT * FROM units WHERE id=?').get(ctx.user.unit_id),guests:list('SELECT * FROM guests WHERE tenant_id=? AND unit_id=? ORDER BY created_at DESC',ctx.tenantId,ctx.user.unit_id),packages:list('SELECT * FROM packages WHERE tenant_id=? AND unit_id=? ORDER BY created_at DESC',ctx.tenantId,ctx.user.unit_id),tickets:list('SELECT * FROM tickets WHERE tenant_id=? AND unit_id=? ORDER BY created_at DESC',ctx.tenantId,ctx.user.unit_id),bookings:list('SELECT * FROM bookings WHERE tenant_id=? AND unit_id=?',ctx.tenantId,ctx.user.unit_id)};if(ctx.user.role==='guard')return {...common,guests:list("SELECT * FROM guests WHERE tenant_id=? AND status IN ('waiting','approved','entered')",ctx.tenantId),packages:list("SELECT p.*,u.code unit_code FROM packages p JOIN units u ON u.id=p.unit_id WHERE p.tenant_id=? AND p.status!='collected'",ctx.tenantId)};if(ctx.user.role==='manager')return {...common,tickets:list("SELECT * FROM tickets WHERE tenant_id=? AND status NOT IN ('closed') ORDER BY CASE priority WHEN 'critical' THEN 1 WHEN 'urgent' THEN 2 ELSE 3 END",ctx.tenantId)};return {...common,receipts:list("SELECT r.*,u.code unit_code FROM receipts r JOIN units u ON u.id=r.unit_id WHERE r.tenant_id=? AND r.status='submitted'",ctx.tenantId)}},
 createGuest(ctx,input){requireRole(ctx,'resident');const gid=id();db.prepare('INSERT INTO guests VALUES(?,?,?,?,?,?,?,?,?,?)').run(gid,ctx.tenantId,ctx.user.unit_id,input.name,input.type||'personal','approved',input.valid_until||new Date(Date.now()+7200000).toISOString(),1,ctx.user.id,now());audit(ctx,'guest.create','guest',gid);return db.prepare('SELECT * FROM guests WHERE id=?').get(gid)},
 transitionGuest(ctx,gid,status,expectedVersion){requireRole(ctx,'resident','guard','manager');const g=db.prepare('SELECT * FROM guests WHERE id=? AND tenant_id=?').get(gid,ctx.tenantId);if(!g)throw err(404,'NOT_FOUND');if(ctx.user.role==='resident')ownUnit(ctx,g.unit_id);const allowed={waiting:['approved','rejected'],approved:['entered','rejected'],entered:['exited']}[g.status]||[];if(!allowed.includes(status))throw err(409,'INVALID_TRANSITION');if(g.version!==expectedVersion)throw err(409,'CONFLICT');db.prepare('UPDATE guests SET status=?,version=version+1 WHERE id=?').run(status,gid);audit(ctx,`guest.${status}`,'guest',gid);return db.prepare('SELECT * FROM guests WHERE id=?').get(gid)},
 createTicket(ctx,input){requireRole(ctx,'resident');const tid=id();db.prepare('INSERT INTO tickets VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(tid,ctx.tenantId,ctx.user.unit_id,input.category,input.title,input.priority||'normal','submitted',null,1,ctx.user.id,now());audit(ctx,'ticket.create','ticket',tid);return db.prepare('SELECT * FROM tickets WHERE id=?').get(tid)},
 transitionTicket(ctx,tid,input){requireRole(ctx,'manager');const t=db.prepare('SELECT * FROM tickets WHERE id=? AND tenant_id=?').get(tid,ctx.tenantId);if(!t)throw err(404,'NOT_FOUND');if(t.version!==input.expected_version)throw err(409,'CONFLICT');db.prepare('UPDATE tickets SET status=?,assignee=?,version=version+1 WHERE id=?').run(input.status,input.assignee||t.assignee,tid);audit(ctx,`ticket.${input.status}`,'ticket',tid);return db.prepare('SELECT * FROM tickets WHERE id=?').get(tid)},
 createBooking(ctx,input){requireRole(ctx,'resident');const clash=db.prepare("SELECT 1 FROM bookings WHERE tenant_id=? AND amenity=? AND status='confirmed' AND start_at < ? AND end_at > ?").get(ctx.tenantId,input.amenity,input.end_at,input.start_at);if(clash)throw err(409,'BOOKING_CONFLICT');const bid=id();db.prepare('INSERT INTO bookings VALUES(?,?,?,?,?,?,?,?,?)').run(bid,ctx.tenantId,ctx.user.unit_id,input.amenity,input.start_at,input.end_at,'confirmed',ctx.user.id,now());audit(ctx,'booking.confirm','booking',bid);return db.prepare('SELECT * FROM bookings WHERE id=?').get(bid)},
 submitReceipt(ctx,input){requireRole(ctx,'resident');const fp=createHash('sha256').update(`${ctx.user.unit_id}|${input.amount}|${input.paid_at}`).digest('hex');const rid=id();try{db.prepare('INSERT INTO receipts VALUES(?,?,?,?,?,?,?,?)').run(rid,ctx.tenantId,ctx.user.unit_id,input.amount,'submitted',fp,ctx.user.id,now())}catch{throw err(409,'DUPLICATE_RECEIPT')}audit(ctx,'receipt.submit','receipt',rid);return db.prepare('SELECT * FROM receipts WHERE id=?').get(rid)},
 reviewReceipt(ctx,rid,status){requireRole(ctx,'accountant');if(!['approved','rejected'].includes(status))throw err(422,'VALIDATION_FAILED');const r=db.prepare('SELECT * FROM receipts WHERE id=? AND tenant_id=?').get(rid,ctx.tenantId);if(!r)throw err(404,'NOT_FOUND');db.prepare('UPDATE receipts SET status=? WHERE id=?').run(status,rid);audit(ctx,`receipt.${status}`,'receipt',rid);return db.prepare('SELECT * FROM receipts WHERE id=?').get(rid)},
 receivePackage(ctx,input){requireRole(ctx,'guard');const unit=db.prepare('SELECT * FROM units WHERE tenant_id=? AND code=?').get(ctx.tenantId,input.unit_code);if(!unit)throw err(404,'UNIT_NOT_FOUND');const pid=id();db.prepare('INSERT INTO packages VALUES(?,?,?,?,?,?,?,?,?,?)').run(pid,ctx.tenantId,unit.id,input.carrier||null,input.reference||null,'received',ctx.user.id,null,now(),now());db.prepare('INSERT INTO notification_intents VALUES(?,?,?,?,?,?,?,?,?)').run(id(),ctx.tenantId,null,unit.id,'package.received',pid,JSON.stringify({unit_code:unit.code}), 'pending',now());audit(ctx,'package.receive','package',pid);return db.prepare('SELECT * FROM packages WHERE id=?').get(pid)},
 collectPackage(ctx,pid){requireRole(ctx,'resident','guard');const p=db.prepare('SELECT * FROM packages WHERE id=? AND tenant_id=?').get(pid,ctx.tenantId);if(!p)throw err(404,'NOT_FOUND');if(ctx.user.role==='resident')ownUnit(ctx,p.unit_id);if(p.status!=='received')throw err(409,'INVALID_TRANSITION');db.prepare("UPDATE packages SET status='collected',collected_by=?,updated_at=? WHERE id=?").run(ctx.user.id,now(),pid);audit(ctx,'package.collect','package',pid);return db.prepare('SELECT * FROM packages WHERE id=?').get(pid)},
 createNotice(ctx,input){requireRole(ctx,'manager');const nid=id();db.prepare('INSERT INTO notices VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(nid,ctx.tenantId,input.title_fa,input.title_en||'',input.body_fa,input.body_en||'',input.audience||'all','draft',1,ctx.user.id,now(),null);audit(ctx,'notice.create','notice',nid);return db.prepare('SELECT * FROM notices WHERE id=?').get(nid)},
 publishNotice(ctx,nid,expectedVersion){requireRole(ctx,'manager');const n=db.prepare('SELECT * FROM notices WHERE id=? AND tenant_id=?').get(nid,ctx.tenantId);if(!n)throw err(404,'NOT_FOUND');if(n.version!==expectedVersion)throw err(409,'CONFLICT');if(n.status!=='draft')throw err(409,'INVALID_TRANSITION');db.prepare("UPDATE notices SET status='published',version=version+1,published_at=? WHERE id=?").run(now(),nid);db.prepare('INSERT INTO notification_intents VALUES(?,?,?,?,?,?,?,?,?)').run(id(),ctx.tenantId,null,null,'notice.published',nid,JSON.stringify({audience:n.audience}), 'pending',now());audit(ctx,'notice.publish','notice',nid);return db.prepare('SELECT * FROM notices WHERE id=?').get(nid)},
 assistant(ctx,question){requireRole(ctx,...roles);const q=String(question||'').toLowerCase();let answer,sources=[];if(ctx.user.role==='resident'&&(q.includes('شارژ')||q.includes('balance'))){const unit=db.prepare('SELECT code,balance FROM units WHERE id=?').get(ctx.user.unit_id);answer={fa:`مانده نمونه واحد ${unit.code} برابر ${unit.balance/10} تومان است.`,en:`The synthetic balance for ${unit.code} is ${unit.balance/10} toman.`};sources=['unit.statement']}else if(ctx.user.role==='manager'){const count=db.prepare("SELECT count(*) n FROM tickets WHERE tenant_id=? AND status!='closed'").get(ctx.tenantId).n;answer={fa:`${count} درخواست باز در داده نمونه وجود دارد.`,en:`There are ${count} open synthetic tickets.`};sources=['operations.tickets']}else{answer={fa:'برای این پرسش داده تأییدشده کافی ندارم.',en:'I do not have enough approved data for this question.'};sources=[]}audit(ctx,'ai.read','ai_interaction',null);return {answer:answer.fa,answer_en:answer.en,sources,proposed:true}},
 auditLog(ctx){requireRole(ctx,'manager','accountant');return list('SELECT * FROM audit WHERE tenant_id=? ORDER BY created_at DESC',ctx.tenantId)}}}
export function err(status,code,message=code){return Object.assign(new Error(message),{status,code})}
